import type { NextPage } from "next";
import Head from "next/head";
import About from "../components/about";
import Contact from "../components/contact";
import Footer from "../components/footer";
import Masthead from "../components/masthead";
import Skills from "../components/skills";
import Trusted from "../components/trusted";
import Works from "../components/works";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Agency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Masthead />
      <About />
      <Skills />
      <Works />
      <Trusted />
      <Contact />
      <Footer />
    </div>
  );
};

export default Home;
